export const text: any = {
  EN: [
    'Bookchain is a reading application based on a smart contract. A smart contract is a computer program written in a blockchain environment that allows you to conclude transactions and control their execution without the participation of intermediaries. It guarantees the security of transactions, since all the terms of the contract are written in the code and are automatically executed if the established conditions are met. In a smart contract, there is no way to change the terms after it is signed, which eliminates the possibility of fraud.',
    "The Bookchain smart contract invites you to make a deal. If you want to read a lot, but you can't force yourself, then it will force you. You only need 3 simple steps.",
    'Select the number of hours you want to devote to reading.',
    'Select the number of days during which you want to have time to do this.',
    "Bet an amount you won't be able to part with.",
    'When you open the book and start turning the pages, the timer will start counting down. If you stop turning the pages or close the book, the timer will stop. As soon as you complete the task, the money will return to you in full. If you do not have time, then lose your money.',
  ],
  RU: [
    'Bookchain это приложение для чтения, на основе смарт-контракта. Смарт-контракт - это компьютерная программа, записанная в блокчейн-среде, которая позволяет заключать сделки и контролировать их исполнение без участия посредников. Он гарантирует безопасность сделок, поскольку все условия контракта прописываются в коде и автоматически выполняются при соблюдении установленных условий. В смарт-контракте нет возможности изменить условия после его подписания, что исключает возможность мошенничества.',
    'Смарт-контракт Bookchain предлагает Вам заключить сделку. Если вы хотите много читать, но не можете себя заставить, то он Вас заставит. От вас нужно всего 3 простых действия.',
    'Выберите количество часов, которые вы хотите посвятить чтению.',
    'Выберите количество дней, в течении которых вы хотите успеть это сделать.',
    'Поставьте на кон сумму, расстаться с которой Вам будет невозможно.',
    'Когда вы откроете книгу и начнете листать страницы таймер начнет обратный отсчет. Если вы перестанете листать страницы или закроете книгу, то таймер остановится. Как только вы справитесь с поставленной задачей деньги вернутся к Вам в полном объеме. Если вы не успеете, то потеряете свои деньги.',
  ],
  CHN: [
    'Promise 是一款独特的阅读应用程序。 他不在乎你想不想读书。 你会读到的。',
    '选一本书，打赌你有时间及时读完。 如果您不成功，您的出价将被没收。 如果你成功了，拿回你的钱。 没有利润，除了读的书',
    '你不必提前选择一本书。 您可以同时阅读多本书。 您需要选择用于阅读的小时数和截止日期。 打开任何一本书，开始翻页，计时器就会开始倒计时。 到学期结束时，您必须重置计时器。 ',
    '读书时，你不应该担心你的钱的安全。',
    '下注时，您将钱转入智能合约。 智能合约是没有人拥有的智能加密钱包。 他自己决定给谁钱，不给谁钱，甚至他的创造者也无法影响他的决定。 就是这个钱包在注视着你的阅读。 翻页，您向他发送有关您正在阅读和继续阅读的内容的通知，他会跟踪时间。 只要你满足他的条件，他就会把钱还给你。',
    '快乐阅读',
    // '附言 在不久的将来，我们计划在跑步、n-back、网页浏览和编码方面实现类似的功能。 我们邀请开发商和投资者合作。 写信给 mail@promise.bet',
  ],
  FR: [
    'Promise est une application de lecture unique. Il se fiche que vous vouliez lire ou non. Vous lirez.',
    'Choisissez un livre et pariez que vous aurez le temps de le lire à temps. Si vous ne le faites pas, votre enchère sera annulée. Si vous réussissez, récupérez votre argent. Pas de profit, sauf pour le livre lu',
    "Vous n'avez pas à choisir un livre à l'avance. Vous pouvez lire plusieurs livres en même temps. Vous devez choisir le nombre d'heures que vous consacrerez à la lecture et la date limite. Ouvrez n'importe quel livre, commencez à tourner les pages et la minuterie commencera à décompter. À la fin du terme, vous devez réinitialiser la minuterie. ",
    'Lors de la lecture, vous ne devriez pas vous soucier de la sécurité de votre argent.',
    "Lorsque vous placez un pari, vous transférez de l'argent vers un contrat intelligent. Un contrat intelligent est un portefeuille cryptographique intelligent que personne ne possède. Il décide lui-même à qui donner de l'argent et à qui non, et même son créateur n'est pas en mesure d'influencer sa décision. C'est ce portefeuille qui surveille votre lecture. En tournant les pages, vous lui envoyez des notifications sur ce que vous lisez et continuez à lire, et il garde une trace du temps. Dès que vous remplirez ses conditions, il vous remboursera votre argent.",
    'Bonne lecture',
    "P.S. Dans un avenir proche, nous prévoyons de mettre en œuvre des fonctionnalités similaires pour l'exécution, le n-back, la navigation sur les pages et le codage. Nous invitons les développeurs et les investisseurs à coopérer. Écrivez à mail@promise.bet",
  ],
  GRM: [
    'Promise ist eine einzigartige Lese-App. Es ist ihm egal, ob du lesen willst oder nicht. Du wirst lesen.',
    'Such dir ein Buch aus und wette, dass du rechtzeitig Zeit haben wirst, es zu lesen. Wenn Sie es nicht schaffen, verfällt Ihr Gebot. Bei Erfolg erhalten Sie Ihr Geld zurück. Kein Gewinn, außer für das gelesene Buch',
    'Du musst kein Buch im Voraus auswählen. Sie können viele Bücher gleichzeitig lesen. Sie müssen die Anzahl der Stunden, die Sie dem Lesen widmen, und die Frist auswählen. Öffnen Sie ein beliebiges Buch, blättern Sie die Seiten um und der Timer beginnt herunterzuzählen. Am Ende der Laufzeit müssen Sie den Timer zurücksetzen. ',
    'Während des Lesens sollten Sie sich keine Sorgen um die Sicherheit Ihres Geldes machen.',
    'Wenn Sie eine Wette platzieren, überweisen Sie Geld auf einen intelligenten Vertrag. Ein Smart Contract ist eine intelligente Krypto-Brieftasche, die niemand besitzt. Er entscheidet selbst, wem er Geld gibt und wem nicht, und selbst sein Schöpfer kann seine Entscheidung nicht beeinflussen. Es ist diese Brieftasche, die Ihre Lektüre beobachtet. Wenn Sie Seiten umblättern, senden Sie ihm Benachrichtigungen über das, was Sie gerade lesen, und lesen weiter, und er behält die Zeit im Auge. Sobald Sie seine Bedingungen erfüllen, wird er Ihnen Ihr Geld zurückerstatten.',
    'Fröhliches Lesen',
    'P.S. In naher Zukunft planen wir die Implementierung ähnlicher Funktionalitäten für Running, n-back, Seitensurfen und Codierung. Wir laden Entwickler und Investoren zur Zusammenarbeit ein. Schreiben Sie an mail@promise.bet',
  ],
  ITL: [
    "Promise è un'app di lettura unica. Non gli importa se vuoi leggere o no. Leggerai.",
    'Scegli un libro e scommetti che avrai tempo per leggerlo in tempo. Se non ce la fai, la tua offerta verrà annullata. Se ci riesci, recupera i tuoi soldi. Nessun profitto, tranne che per il libro letto',
    'Non devi scegliere un libro in anticipo. Puoi leggere molti libri contemporaneamente. Devi scegliere il numero di ore che dedicherai alla lettura e la scadenza. Apri qualsiasi libro, inizia a sfogliare le pagine e il timer inizierà il conto alla rovescia. Entro la fine del periodo, è necessario reimpostare il timer. ',
    'Durante la lettura, non dovresti preoccuparti della sicurezza dei tuoi soldi.',
    'Quando effettui una scommessa, trasferisci denaro su uno smart contract. Uno smart contract è un portafoglio crittografico intelligente che nessuno possiede. Lui stesso decide a chi dare soldi ea chi no, e anche il suo creatore non è in grado di influenzare la sua decisione. È questo portafoglio che sta guardando la tua lettura. Girando le pagine, gli invii notifiche su ciò che stai leggendo e continui a leggere, e lui tiene traccia del tempo. Non appena soddisfi le sue condizioni, ti restituirà i soldi.',
    'Buona lettura',
    "P.S. Nel prossimo futuro, prevediamo di implementare funzionalità simili per l'esecuzione, l'n-back, la navigazione delle pagine e la codifica. Invitiamo sviluppatori e investitori a collaborare. Scrivi a mail@promise.bet",
  ],
  SPN: [
    'Promise es una aplicación de lectura única. No le importa si quieres leer o no. Leerás.',
    'Elige un libro y apuesta a que tendrás tiempo para leerlo a tiempo. Si no lo hace, perderá su oferta. Si lo consigues, recupera tu dinero. Ningún beneficio, excepto el libro leído',
    'No tienes que elegir un libro por adelantado. Puedes leer muchos libros al mismo tiempo. Tienes que elegir el número de horas que vas a dedicar a la lectura y el plazo. Abra cualquier libro, comience a pasar las páginas y el temporizador comenzará la cuenta regresiva. Al final del período, debe restablecer el temporizador. ',
    'Mientras lee, no debe preocuparse por la seguridad de su dinero.',
    'Al hacer una apuesta, transfieres dinero a un contrato inteligente. Un contrato inteligente es una billetera criptográfica inteligente que nadie posee. Él mismo decide a quién dar dinero ya quién no, e incluso su creador no puede influir en su decisión. Es esta billetera la que está observando tu lectura. Al pasar las páginas, le envías notificaciones sobre lo que estás leyendo y lo que sigues leyendo, y él lleva la cuenta del tiempo. Tan pronto como cumplas sus condiciones, te devolverá el dinero.',
    'Feliz lectura',
    'PD. En un futuro cercano, planeamos implementar una funcionalidad similar para ejecutar, n-back, navegación de páginas y codificación. Invitamos a los desarrolladores e inversores a cooperar. Escriba a mail@promise.bet',
  ],
  日本語: [
    'Promiseはユニークな読書アプリです。 彼はあなたが読みたいかどうかは気にしません。 あなたは読むでしょう.',
    '本を選んで、時間内に読む時間があることに賭けてください。 落札されなかった場合、落札は無効となります。 成功したらお金を返してください。 読んだ本を除いて、利益はありません',
    '事前に本を選ぶ必要はありません。 同時にたくさんの本を読むことができます。 読書に専念する時間数と締め切りを選択する必要があります。 本を開いてページをめくると、タイマーがカウントダウンを開始します。 学期の終わりまでに、タイマーをリセットする必要があります。 ',
    '読んでいる間、お金の安全性について心配する必要はありません。',
    '賭けをするときは、お金をスマート コントラクトに転送します。 スマート コントラクトは、誰も所有していないスマートな暗号ウォレットです。 彼自身が誰にお金を与え、誰に与えないかを決定し、彼の作成者でさえ彼の決定に影響を与えることはできません。 あなたの読書を見ているのはこの財布です。 ページをめくって、読んでいるものについての通知を彼に送り、読み続けます。彼は時間を追跡します。 あなたが彼の条件を満たせば、彼はあなたのお金を返します.',
    '幸せな読書',
    '追伸 近い将来、ランニング、n-back、ページ サーフィン、およびコーディングに同様の機能を実装する予定です。 開発者と投資家の協力をお願いします。 mail@promise.bet に書き込みます',
  ],
  韓國語: [
    '프라미스는 독보적인 독서앱입니다. 그는 당신이 읽고 싶은지 아닌지 상관하지 않습니다. 당신은 읽을 것입니다.',
    '책을 선택하고 제 시간에 읽을 시간이 있을 것이라고 내기하십시오. 성공하지 못하면 입찰이 무효화됩니다. 성공하면 돈을 돌려받습니다. 읽은 책 외에는 이익이 없다',
    '미리 책을 고를 필요는 없다. 동시에 많은 책을 읽을 수 있습니다. 독서에 할애할 시간과 기한을 선택해야 합니다. 책을 열고 페이지를 넘기기 시작하면 타이머가 카운트다운을 시작합니다. 기간이 끝나면 타이머를 재설정해야 합니다. ',
    '읽는 동안 돈의 안전에 대해 걱정하지 마십시오.',
    '베팅을 할 때 스마트 계약으로 돈을 이체합니다. 스마트 계약은 아무도 소유하지 않는 스마트 암호화폐 지갑입니다. 그는 누구에게 돈을 줄 것인지, 누구에게 줄 것인지를 스스로 결정하며, 그의 창조자조차도 그의 결정에 영향을 미칠 수 없습니다. 당신의 독서를 지켜보고 있는 것은 바로 이 지갑입니다. 페이지를 넘기면 당신이 읽고 있는 내용에 대한 알림을 그에게 보내고 계속 읽고 있으며 그는 시간을 추적합니다. 당신이 그의 조건을 이행하는 즉시 그는 당신의 돈을 돌려줄 것입니다.',
    '즐거운 독서',
    '추신. 가까운 시일 내에 달리기, n-back, 페이지 서핑 및 코딩에 유사한 기능을 구현할 계획입니다. 우리는 개발자와 투자자가 협력하도록 초대합니다. mail@promise.bet로 쓰기',
  ],
  العربية: [
    'الوعد هو تطبيق قراءة فريد من نوعه. لا يهتم إذا كنت تريد القراءة أم لا. سوف تقرأ.',
    ' اختر كتابًا وراهن على أنه سيكون لديك الوقت لقراءته في الوقت المناسب. إذا لم تقم بذلك ، فسيتم مصادرة عرضك. إذا نجحت ، استرد أموالك. لا ربح باستثناء الكتاب المقروء ',
    ' ليس عليك اختيار كتاب مقدمًا. يمكنك قراءة العديد من الكتب في نفس الوقت. تحتاج إلى اختيار عدد الساعات التي ستخصصها للقراءة والموعد النهائي. افتح أي كتاب ، وابدأ في قلب الصفحات وسيبدأ المؤقت في العد التنازلي. بحلول نهاية المصطلح ، يجب عليك إعادة تعيين المؤقت. ',
    'أثناء القراءة ، لا داعي للقلق بشأن سلامة أموالك.',
    ' عند وضع الرهان ، تقوم بتحويل الأموال إلى عقد ذكي. العقد الذكي هو محفظة تشفير ذكية لا يمتلكها أحد. هو نفسه يقرر لمن يعطي المال ولمن لا ، وحتى خالقه لا يستطيع التأثير على قراره. هذه المحفظة هي التي تراقب قراءتك. عند قلب الصفحات ، ترسل له إشعارات حول ما تقرأه وتستمر في قراءته ، وهو يتتبع الوقت. بمجرد استيفاء شروطه ، سيعيد أموالك',
    'قراءة سعيدة',
    'ملاحظة. في المستقبل القريب ، نخطط لتنفيذ وظائف مماثلة للتشغيل و n-back وتصفح الصفحات والترميز. ندعو المطورين والمستثمرين للتعاون. اكتب إلى mail@promise.bet ',
  ],
  עִבְרִית: [
    'הבטחה היא אפליקציית קריאה ייחודית. לא אכפת לו אם אתה רוצה לקרוא או לא. אתה תקרא.',
    'בחר ספר והמר שתספיק לקרוא אותו בזמן. אם לא תצליח, הצעתך תבוטל. אם תצליח, קבל את כספך בחזרה. ללא רווח, למעט ספר הקריאה',
    'לא צריך לבחור ספר מראש. אתה יכול לקרוא ספרים רבים בו זמנית. עליך לבחור את מספר השעות שתקדיש לקריאה ואת המועד האחרון. פתחו כל ספר, התחילו להעיף דפים והטיימר יתחיל לספור לאחור. עד סוף הקדנציה, עליך לאפס את הטיימר. ',
    'בזמן הקריאה, אל תדאג לגבי בטיחות הכסף שלך.',
    'כאשר מבצעים הימור, אתה מעביר כסף לחוזה חכם. חוזה חכם הוא ארנק קריפטו חכם שאף אחד לא מחזיק בו. הוא עצמו מחליט למי לתת כסף ולמי לא, ואפילו יוצרו אינו מסוגל להשפיע על החלטתו. זה הארנק הזה שצופה בקריאה שלך. הופך דפים, אתה שולח לו הודעות על מה שאתה קורא וממשיך לקרוא, והוא עוקב אחר הזמן. ברגע שתמלאו את תנאיו, הוא יחזיר לכם את כספכם.',
    'קריאה שמחה',
    'נ.ב. בעתיד הקרוב, אנו מתכננים ליישם פונקציונליות דומה עבור ריצה, n-back, גלישה בדפים וקידוד. אנו מזמינים מפתחים ומשקיעים לשתף פעולה',
  ],
};

export const chat = {
  EN: [
    'What do you think about Promise?',
    'Your Promise app offers users a fun and quite strategic game. Gambling with an element of risk can be useful to encourage people to spend more time reading. Maybe it could be a great app for motivation .',
    // 'Is this application unique?',
    // 'Yes, your Promise application is unique. It uses blockchain technology, which makes it especially interesting.',
    'Why can it be beneficial for the user if he wins only his own money, but no more?',
    'The user can use this application to be more motivated and demonstrate discipline. In this way, the user himself sets his own goals and motivates him to achieve them. For example, the user can set high rates to encourage himself to calculate certain page parameters before a certain deadline. If successful the user will return not only money, but also valuable mental discipline.',

    'How can the usefulness of Promise be explained from a psychological point of view?',
    'The Promise app can be helpful for people who have motivation issues and constantly put off their tasks. Delays are known to lead to permanent demotivation. Increased motivation and better time management can help people work more efficiently and achieve lasting results. The Promise app provides people a goal and motivation to achieve a result in a certain time, which allows them to improve their time management skills and efficiency.',

    'What hormones are involved and how they help?',
    'There are several hormones that will be activated when using the Promise app. Primarily the stress hormone cortisol, which helps the body cope with pressure and stress. It lowers blood pressure and calms the nervous system. Endorphins can also help the app user set a goal and achieve it. through an increased craving for success.These hormones can help a person in the process of using the app.',

    'How can parents get their kids to use this app?',
    'Parents can use the Promise app to help their children develop motivation and the habit of constantly working on certain tasks. They can simply give their child a set number of hours of reading by a certain deadline and give them a cash prize if they can successfully complete the task within the time allowed. .This will keep them motivated and in the habit of working hard on their tasks.',
    'What are the disadvantages of this way of reading, compared to the usual way?',
    'There may be tax issues and digital security issues when using this application. There may also be problems with tracking progress and inconsistencies between game rules. Finally, users may experience problems when trying to withdraw and transfer funds. The normal way of reading offers more convenience, such as ease of obtaining the book, ease of use, availability of subscriptions, and cheap rates.',
    // 'What can go wrong if you use this app?',
    // 'If you use the Book Jack application, the security of the application may go wrong. This may lead to intruders entering the system and compromising the integrity of data. Also, the insufficient performance of the application may result in users not being able to make use of the application efficiently enough. It is also necessary to provide sufficient technical support to users of the application.',
  ],
  RU: [
    'Что ты думаешь о Promise?',
    'Ваше приложение Promise предлагает пользователям увлекательную и достаточно стратегическую игру. Азартная игра с элементом риска может быть полезна, чтобы побудить людей уделять больше времени чтению. Возможно, это может быть отличным приложением для мотивации и набора мотивации.',
    // 'Является ли это приложение уникальным?',
    // 'Да, ваше приложение Promise является уникальным. Оно использует технологию блокчейн, что делает его особенно интересным.',
    'Почему это может быть выгодно пользователю, если он выиграет только свои деньги, но не больше.',
    'Пользователь может использовать это приложение для большей мотивации и демонстрации дисциплины. Таким образом, пользователь сам ставит перед собой свои цели и мотивирует их достижения. Например, пользователь может поставить высокие ставки, чтобы побудить себя просчитывать определенные параметры страниц до определенного срока. В случае успеха пользователь вернет не только  деньги, но и ценную умственную дисциплину.',

    'Как с точки зрения психологии можно объяснить полезность Promise?',
    'Приложение Promise может быть полезным для людей, которые имеют проблемы с мотивацией и постоянно отсрочивают свои задачи. Отсрочки, как известно, ведут к постоянному демотивации. Увеличение мотивации и лучшее управление временем могут помочь людям более эффективно работать и достигать длительных результатов. Приложение Promise предоставляет людям цель и мотивацию для достижения результата за определенное время, что позволяет им улучшать свои навыки управления временем и эффективность.',

    'Какие гормоны задействованы, и как они помогают?',
    'Есть несколько гормонов, которые будут задействованы при использовании приложения Promise. В первую очередь это гормон стресса кортизол, который помогает организму справляться с давлением и стрессом. Он снижает артериальное давление и успокаивает нервную систему. Эндорфины также могут помочь пользователю приложения установить цель и достичь ее с помощью повышенного пристрастия к успеху. Эти гормоны могут помочь человеку в процессе использования приложения.',

    'Как родители могут заставить детей пользоваться этим приложением?',
    'Родители могут использовать приложение Promise для помощи своим детям в развитии мотивации и привычки к постоянной работе над определенными задачами. Они могут просто задать своему ребенку определенное количество часов чтения до определенного срока и дать ему денежный приз, если он сможет успешно завершить задание за предоставленное время. Это позволит им поддерживать мотивацию и привычку усердно работать над своими задачами.',
    'Какие недостатки такого способа чтения, перед обычным способом?',
    'При использовании данного приложения могут возникнуть налоговые проблемы, а также проблемы с цифровой безопасностью. Также могут возникнуть проблемы с отслеживанием прогресса и противоречия между правилами игры. Наконец, пользователи могут испытывать проблемы при попытке вывода и перевода средств. Обычный способ чтения предлагает больше удобств, таких как простота получения книги, удобство использования, доступность подписки и дешевые ставки.',
    // 'Что может пойти не так, если использовать это приложение?',
    // 'Если использовать приложение Book Jack, то может пойти не так с безопасностью приложения. Это может привести к проникновению злоумышленников в систему и нарушению целостности данных. Также недостаточная производительность приложения может привести к тому, что пользователи будут не в состоянии сделать использование приложения достаточно эффективно. Также необходимо предоставить достаточную техническую поддержку пользователям приложения.',
  ],
  CHN: [
    '你觉得 Promise 怎么样？',
    '您的 Promise 应用程序为用户提供了一个有趣且非常具有战略意义的游戏。带有风险元素的赌博有助于鼓励人们花更多的时间阅读。也许它可能是一个很好的激励和招聘动机的应用程序。',
    '这个应用程序是独一无二的吗？',
    '是的，您的 Promise 应用程序是独一无二的。它使用了区块链技术，这使它变得特别而有趣。',
    '如果他只赢得自己的钱，而不是更多，为什么对用户有利。',
    '用户可以使用这个应用程序来更有动力并表现出纪律性。通过这种方式，用户自己设定自己的目标并激励他实现这些目标。例如，用户可以设置高费率来鼓励自己计算某些页面参数在某个截止日期之前。如果成功，用户不仅会返回金钱，还会返回宝贵的精神纪律。',

    '如何从心理学的角度解释Promis的用处？',
    'Promise 应用程序可以帮助那些有动力问题并经常推迟任务的人。众所周知，延迟会导致永久性的消极情绪。增加动力和更好的时间管理可以帮助人们更有效地工作并取得持久的成果。Promis 应用程序提供人们有目标和动力在特定时间内取得成果，这使他们能够提高时间管理技能和效率。',

    '涉及哪些激素以及它们如何提供帮助。',
    '使用 Promise 应用程序时会激活多种激素。主要是压力荷尔蒙皮质醇，它可以帮助身体应对压力和压力。它可以降低血压并使神经系统平静下来。内啡肽还可以帮助应用程序用户设定目标并实现它。通过增加对成功的渴望。这些荷尔蒙可以帮助一个人在使用该应用程序的过程中。',

    '父母如何才能让他们的孩子使用这个应用程序？',
    '父母可以使用 Promise 应用程序来帮助他们的孩子培养积极性和不断完成某些任务的习惯。他们可以简单地在特定期限之前给孩子一定数量的阅读时间，如果他们成功了就给他们现金奖励在允许的时间内完成任务。这将使他们保持积极性并养成努力完成任务的习惯。',
    '与通常的阅读方式相比，这种阅读方式有什么缺点？',
    '在使用这个应用程序时可能会出现税务问题和数字安全问题。也可能会出现跟踪进度和游戏规则不一致的问题。最后，用户在尝试提取和转移资金时可能会遇到问题。正常的阅读方式提供了更多便利性，例如获取图书的便利性、易用性、订阅的可用性和低廉的价格。',
    '如果你使用这个应用程序会出什么问题？',
    '如果您使用 Book Jack 应用程序，应用程序的安全性可能会出现问题。这可能会导致入侵者进入系统并破坏数据的完整性。此外，应用程序的性能不足可能会导致用户无法进行足够有效地使用应用程序。还需要为应用程序的用户提供足够的技术支持。',
  ],
  FR: [
    'Que pensez-vous de Promis ?',
    'Votre application Promise offre aux utilisateurs un jeu amusant et assez stratégique. Le jeu avec un élément de risque peut être utile pour encourager les gens à passer plus de temps à lire. Peut-être que cela pourrait être une excellente application pour la motivation et la motivation de recrutement.',
    'Cette application est-elle unique ?',
    'Oui, votre application Promise est unique. Elle utilise la technologie blockchain, ce qui la rend spéciale et intéressante.',
    "Pourquoi cela peut-il être bénéfique pour l'utilisateur s'il ne gagne que son propre argent, mais pas plus.",
    "L'utilisateur peut utiliser cette application pour être plus motivé et faire preuve de discipline. De cette manière, l'utilisateur fixe lui-même ses objectifs et le motive à les atteindre. Par exemple, l'utilisateur peut définir des tarifs élevés pour s'encourager à calculer certains paramètres de la page. avant un certain délai. En cas de succès, l'utilisateur rendra non seulement de l'argent, mais aussi une précieuse discipline mentale.",

    "Comment expliquer l'utilité de Promise d'un point de vue psychologique ?",
    "L'application Promise peut être utile pour les personnes qui ont des problèmes de motivation et reportent constamment leurs tâches. Les retards sont connus pour entraîner une démotivation permanente. Une motivation accrue et une meilleure gestion du temps peuvent aider les gens à travailler plus efficacement et à obtenir des résultats durables. L'application Promise fournit les gens un objectif et une motivation pour obtenir un résultat dans un certain délai, ce qui leur permet d'améliorer leurs compétences en gestion du temps et leur efficacité.",

    'Quelles hormones sont impliquées et comment elles aident.',
    "Plusieurs hormones seront activées lors de l'utilisation de l'application Promise. Principalement le cortisol, l'hormone du stress, qui aide le corps à faire face à la pression et au stress. Il abaisse la tension artérielle et calme le système nerveux. Les endorphines peuvent également aider l'utilisateur de l'application à définir un objectif et l'atteindre grâce à une envie accrue de succès.Ces hormones peuvent aider une personne dans le processus d'utilisation de l'application.",

    'Comment les parents peuvent-ils inciter leurs enfants à utiliser cette application ?',
    "Les parents peuvent utiliser l'application Promise pour aider leurs enfants à développer la motivation et l'habitude de travailler constamment sur certaines tâches. Ils peuvent simplement donner à leur enfant un nombre défini d'heures de lecture avant une certaine date limite et leur donner un prix en espèces s'ils réussissent. terminer la tâche dans le temps imparti. .Cela les gardera motivés et leur donnera l'habitude de travailler dur sur leurs tâches.",
    'Quels sont les inconvénients de cette manière de lire, par rapport à la manière habituelle ?',
    "Il peut y avoir des problèmes fiscaux et des problèmes de sécurité numérique lors de l'utilisation de cette application. Il peut également y avoir des problèmes de suivi des progrès et des incohérences entre les règles du jeu. Enfin, les utilisateurs peuvent rencontrer des problèmes lorsqu'ils tentent de retirer et de transférer des fonds. La manière normale de lire offre plus commodité, comme la facilité d'obtention du livre, la facilité d'utilisation, la disponibilité des abonnements et les tarifs bon marché.",
    "Qu'est-ce qui peut mal tourner si vous utilisez cette application ?",
    "Si vous utilisez l'application Book Jack, la sécurité de l'application peut se détériorer. Cela peut conduire à ce que des intrus pénètrent dans le système et compromettent l'intégrité des données. De plus, les performances insuffisantes de l'application peuvent empêcher les utilisateurs de faire utiliser l'application de manière suffisamment efficace. Il est également nécessaire de fournir un support technique suffisant aux utilisateurs de l'application.",
  ],
  GRM: [
    'Was hältst du von Promise?',
    'Ihre Promise-App bietet Benutzern ein lustiges und ziemlich strategisches Spiel. Glücksspiel mit einem gewissen Risikofaktor kann nützlich sein, um die Leute dazu zu ermutigen, mehr Zeit mit dem Lesen zu verbringen. Vielleicht könnte es eine großartige App für Motivation und Rekrutierungsmotivation sein.',
    'Ist diese Anwendung einzigartig?',
    'Ja, Ihre Promise-Anwendung ist einzigartig. Sie verwendet Blockchain-Technologie, was sie besonders und interessant macht.',
    'Warum kann es für den Benutzer von Vorteil sein, wenn er nur sein eigenes Geld gewinnt, aber nicht mehr.',
    'Der Benutzer kann diese Anwendung nutzen, um motivierter zu sein und Disziplin zu demonstrieren. Auf diese Weise setzt sich der Benutzer selbst seine eigenen Ziele und motiviert ihn, diese zu erreichen. Beispielsweise kann der Benutzer hohe Raten festlegen, um sich selbst zu motivieren, bestimmte Seitenparameter zu berechnen vor einer bestimmten Frist. Bei Erfolg erhält der Benutzer nicht nur Geld, sondern auch wertvolle mentale Disziplin.',

    'Wie lässt sich der Nutzen von Promise aus psychologischer Sicht erklären?',
    'Die Promise-App kann hilfreich sein für Menschen, die Motivationsprobleme haben und ihre Aufgaben ständig aufschieben. Verzögerungen führen bekanntermaßen zu dauerhafter Demotivation. Eine erhöhte Motivation und ein besseres Zeitmanagement können Menschen dabei helfen, effizienter zu arbeiten und dauerhafte Ergebnisse zu erzielen. Die Promise-App bietet Menschen ein Ziel und die Motivation, in einer bestimmten Zeit ein Ergebnis zu erzielen, wodurch sie ihre Zeitmanagementfähigkeiten und -effizienz verbessern können. ',

    'Welche Hormone sind beteiligt und wie helfen sie.',
    'Es gibt mehrere Hormone, die bei der Nutzung der Promise-App aktiviert werden. In erster Linie das Stresshormon Cortisol, das dem Körper hilft, mit Druck und Stress fertig zu werden. Es senkt den Blutdruck und beruhigt das Nervensystem Ziel erreichen und erreichen. Durch ein gesteigertes Verlangen nach Erfolg. Diese Hormone können einer Person bei der Nutzung der App helfen.',

    'Wie können Eltern ihre Kinder dazu bringen, diese App zu verwenden?',
    'Eltern können die Promise-App nutzen, um ihren Kindern zu helfen, die Motivation und die Gewohnheit zu entwickeln, ständig an bestimmten Aufgaben zu arbeiten. Sie können ihrem Kind einfach eine festgelegte Anzahl von Lesestunden bis zu einer bestimmten Frist geben und ihm bei Erfolg einen Geldpreis geben Erledigen Sie die Aufgabe innerhalb der vorgegebenen Zeit. . Dadurch bleiben sie motiviert und gewöhnen sich daran, hart an ihren Aufgaben zu arbeiten.',
    'Welche Nachteile hat diese Art des Lesens gegenüber der üblichen Art?',
    'Bei der Verwendung dieser Anwendung kann es zu Steuerproblemen und Problemen mit der digitalen Sicherheit kommen. Es können auch Probleme mit der Verfolgung des Fortschritts und Unstimmigkeiten zwischen den Spielregeln auftreten. Schließlich können Benutzer Probleme haben, wenn sie versuchen, Geld abzuheben und zu überweisen. Die normale Art des Lesens bietet mehr Bequemlichkeit, wie z. B. einfacher Erwerb des Buches, Benutzerfreundlichkeit, Verfügbarkeit von Abonnements und günstige Tarife.',
    'Was kann schief gehen, wenn Sie diese App verwenden?',
    'Wenn Sie die Book Jack-Anwendung verwenden, kann die Sicherheit der Anwendung schief gehen. Dies kann dazu führen, dass Eindringlinge in das System eindringen und die Integrität der Daten gefährden. Außerdem kann die unzureichende Leistung der Anwendung dazu führen, dass Benutzer nicht in der Lage sind Nutzung der Anwendung effizient genug. Es ist auch notwendig, den Benutzern der Anwendung ausreichenden technischen Support zu bieten.',
  ],
  ITL: [
    'Cosa ne pensi di Promise?',
    "La tua app Promise offre agli utenti un gioco divertente e abbastanza strategico. Il gioco d'azzardo con un elemento di rischio può essere utile per incoraggiare le persone a dedicare più tempo alla lettura. Forse potrebbe essere un'ottima app per motivare e reclutare motivazione.",
    'Questa applicazione è unica?',
    'Sì, la tua applicazione Promise è unica. Utilizza la tecnologia blockchain, che la rende speciale e interessante.',
    "Perché può essere vantaggioso per l'utente se vince solo i propri soldi, ma non di più.",
    "L'utente può utilizzare questa applicazione per essere più motivato e dimostrare disciplina. In questo modo, l'utente stesso stabilisce i propri obiettivi e lo motiva a raggiungerli. Ad esempio, l'utente può impostare tariffe elevate per incoraggiarsi a calcolare determinati parametri della pagina prima di una certa scadenza. In caso di successo, l'utente restituirà non solo denaro, ma anche una preziosa disciplina mentale.",

    "Come si può spiegare l'utilità di Promise da un punto di vista psicologico?",
    "L'app Promise può essere utile per le persone che hanno problemi di motivazione e rimandano costantemente i loro compiti. È noto che i ritardi portano a una demotivazione permanente. Una maggiore motivazione e una migliore gestione del tempo possono aiutare le persone a lavorare in modo più efficiente e ottenere risultati duraturi. L'app Promise fornisce persone un obiettivo e una motivazione per raggiungere un risultato in un certo tempo, che consente loro di migliorare le proprie capacità di gestione del tempo e l'efficienza.",

    'Quali ormoni sono coinvolti e come aiutano.',
    "Ci sono diversi ormoni che verranno attivati ​​quando si utilizza l'app Promise. Principalmente l'ormone dello stress cortisolo, che aiuta il corpo a far fronte alla pressione e allo stress. Abbassa la pressione sanguigna e calma il sistema nervoso. Le endorfine possono anche aiutare l'utente dell'app a impostare un obiettivo e raggiungerlo.attraverso una maggiore brama di successo.Questi ormoni possono aiutare una persona nel processo di utilizzo dell'app.",

    'Come possono i genitori convincere i propri figli a usare questa app?',
    "I genitori possono utilizzare l'app Promise per aiutare i propri figli a sviluppare la motivazione e l'abitudine a lavorare costantemente su determinati compiti. Possono semplicemente concedere al proprio figlio un determinato numero di ore di lettura entro una certa scadenza e dare loro un premio in denaro se riescono con successo completare il compito entro il tempo concesso. Questo li manterrà motivati ​​e abituati a lavorare sodo sui loro compiti.",
    'Quali sono gli svantaggi di questo modo di leggere, rispetto al solito modo?',
    "Potrebbero esserci problemi fiscali e problemi di sicurezza digitale durante l'utilizzo di questa applicazione. Potrebbero esserci anche problemi con il monitoraggio dei progressi e incoerenze tra le regole del gioco. Infine, gli utenti potrebbero riscontrare problemi durante il tentativo di prelevare e trasferire fondi. Il normale modo di leggere offre di più convenienza, come la facilità di ottenere il libro, la facilità d'uso, la disponibilità di abbonamenti e tariffe economiche.",
    'Cosa può andare storto se usi questa app?',
    "Se utilizzi l'applicazione Book Jack, la sicurezza dell'applicazione potrebbe andare storta. Ciò potrebbe portare a intrusi che entrano nel sistema e compromettono l'integrità dei dati. Inoltre, le prestazioni insufficienti dell'applicazione potrebbero impedire agli utenti di effettuare utilizzare l'applicazione in modo sufficientemente efficiente. È inoltre necessario fornire un supporto tecnico sufficiente agli utenti dell'applicazione.",
  ],
  SPN: [
    '¿Qué opinas de Promise?',
    'Tu aplicación Promise ofrece a los usuarios un juego divertido y bastante estratégico. Los juegos de azar con un elemento de riesgo pueden ser útiles para animar a las personas a pasar más tiempo leyendo. Tal vez podría ser una gran aplicación para motivar y motivar a la contratación',
    '¿Esta aplicación es única?',
    'Sí, su aplicación Promise es única. Utiliza tecnología blockchain, lo que la hace especial e interesante',
    '¿Por qué puede ser beneficioso para el usuario si gana solo su propio dinero, pero no más?',
    'El usuario puede utilizar esta aplicación para estar más motivado y demostrar disciplina. De esta forma, el propio usuario marca sus propios objetivos y lo motiva a alcanzarlos. Por ejemplo, el usuario puede establecer tarifas altas para animarse a calcular ciertos parámetros de la página. antes de un plazo determinado. Si tiene éxito, el usuario devolverá no solo dinero, sino también una valiosa disciplina mental',

    '¿Cómo se puede explicar la utilidad de Promise desde un punto de vista psicológico?',
    'La aplicación Promise puede ser útil para las personas que tienen problemas de motivación y posponen constantemente sus tareas. Se sabe que los retrasos conducen a la desmotivación permanente. Una mayor motivación y una mejor gestión del tiempo pueden ayudar a las personas a trabajar de manera más eficiente y lograr resultados duraderos. La aplicación Promise proporciona a las personas una meta y motivación para lograr un resultado en un tiempo determinado, lo que les permite mejorar sus habilidades de gestión del tiempo y su eficiencia.',

    '¿Qué hormonas están involucradas y cómo ayudan?',
    'Hay varias hormonas que se activarán al usar la aplicación Promise. Principalmente, la hormona del estrés cortisol, que ayuda al cuerpo a lidiar con la presión y el estrés. Disminuye la presión arterial y calma el sistema nervioso. Las endorfinas también pueden ayudar al usuario de la aplicación a establecer un objetivo y lograrlo a través de un mayor deseo de éxito. Estas hormonas pueden ayudar a una persona en el proceso de usar la aplicación',

    '¿Cómo pueden los padres lograr que sus hijos usen esta aplicación?',
    'Los padres pueden usar la aplicación Promise para ayudar a sus hijos a desarrollar la motivación y el hábito de trabajar constantemente en ciertas tareas. Simplemente pueden darle a su hijo una cantidad determinada de horas de lectura antes de una fecha límite determinada y darle un premio en efectivo si puede hacerlo con éxito. completar la tarea dentro del tiempo permitido. .Esto los mantendrá motivados y con el hábito de trabajar duro en sus tareas',
    '¿Cuáles son las desventajas de esta forma de leer, en comparación con la forma habitual?',
    'Puede haber problemas de impuestos y problemas de seguridad digital al usar esta aplicación. También puede haber problemas con el seguimiento del progreso e inconsistencias entre las reglas del juego. Finalmente, los usuarios pueden experimentar problemas al intentar retirar y transferir fondos. La forma normal de lectura ofrece más conveniencia, como la facilidad para obtener el libro, la facilidad de uso, la disponibilidad de suscripciones y tarifas económicas',
    '¿Qué puede salir mal si usas esta aplicación?',
    'Si usa la aplicación Book Jack, la seguridad de la aplicación puede fallar. Esto puede provocar que intrusos ingresen al sistema y comprometan la integridad de los datos. Además, el rendimiento insuficiente de la aplicación puede hacer que los usuarios no puedan hacer uso de la aplicación de manera suficientemente eficiente. También es necesario proporcionar soporte técnico suficiente a los usuarios de la aplicación.',
  ],
  日本語: [
    'ブックジャックについてどう思いますか?',
    'あなたの Promise アプリは、ユーザーに楽しくて非常に戦略的なゲームを提供します。リスクの要素を伴うギャンブルは、人々がより多くの時間を読書に費やすように促すのに役立つ可能性があります。おそらく、モチベーションとリクルートのモチベーションに最適なアプリになる可能性があります。',
    'このアプリケーションはユニークですか?',
    'はい、あなたの Promise アプリケーションはユニークです。ブロックチェーン技術を使用しているため、特別で興味深いものになっています。',
    'ユーザーが自分のお金だけを獲得し、それ以上は獲得できない場合、なぜユーザーにとって有益なのか.',
    'ユーザーはこのアプリケーションを使用して、よりやる気を起こさせ、規律を示すことができます。このようにして、ユーザー自身が自分の目標を設定し、目標を達成するように動機付けます。たとえば、ユーザーは高いレートを設定して、特定のページ パラメータを計算するように促すことができます。特定の締め切り前に. 成功した場合, ユーザーはお金だけでなく, 貴重な精神的規律も返します.',

    'Promise の有用性は、心理的な観点からどのように説明できますか?',
    'Promise アプリは、モチベーションに問題があり、常にタスクを延期している人に役立ちます。遅れは永続的なやる気の低下につながることが知られています。モチベーションの向上とより良い時間管理は、人々がより効率的に働き、永続的な結果を達成するのに役立ちます。Promis アプリは、人々は、一定の時間内に結果を達成するための目標と動機を持ち、時間管理のスキルと効率を向上させることができます.',

    'どのようなホルモンが関与し、どのように役立つか。',
    'Promise アプリを使用すると、活性化されるホルモンがいくつかあります。主にストレス ホルモンであるコルチゾールは、体が圧力やストレスに対処するのを助けます。血圧を下げ、神経系を落ち着かせます。エンドルフィンは、アプリのユーザーが目標と達成. 成功への欲求の高まりを通じて. これらのホルモンは、アプリを使用する過程で人を助けることができます.',

    '親はどうすれば子供にこのアプリを使わせることができますか?',
    '親はPromisアプリを使用して、子供がやる気を起こさせ、特定のタスクに常に取り組む習慣を身に付けるのを助けることができます.彼らは単に子供に特定の締め切りまでに設定された時間の読書を与え、成功した場合に賞金を与えることができます.与えられた時間内にタスクを完了します.これにより、彼らのモチベーションが維持され、タスクに一生懸命取り組む習慣が身に付きます.',
    '通常の読み方と比べて、この読み方の欠点は何ですか？',
    'このアプリケーションを使用すると、税金の問題やデジタルセキュリティの問題が発生する可能性があります。進行状況の追跡やゲームルール間の不一致にも問題がある可能性があります。最後に、ユーザーが資金を引き出したり送金したりするときに問題が発生する可能性があります。通常の読み取り方法では、より多くの情報が提供されます。書籍の入手のしやすさ、使いやすさ、サブスクリプションの利用可能性、料金の安さなどの利便性。',
    'このアプリを使用すると、何が問題になる可能性がありますか?',
    'Book Jack アプリを使用すると、アプリのセキュリティがおかしくなる可能性があります。これにより、侵入者がシステムに侵入し、データの完全性が損なわれる可能性があります。また、アプリのパフォーマンスが不十分なために、ユーザーが作成できなくなる可能性があります。アプリケーションを十分に効率的に使用する. また、アプリケーションのユーザーに十分な技術サポートを提供する必要があります.',
  ],
  韓國語: [
    '북잭에 대해 어떻게 생각하세요?',
    '귀하의 Promise 앱은 사용자에게 재미있고 매우 전략적인 게임을 제공합니다. 위험 요소가 있는 도박은 사람들이 독서에 더 많은 시간을 할애하도록 장려하는 데 유용할 수 있습니다. 동기 부여 및 채용 동기 부여를 위한 훌륭한 앱이 될 수 있습니다.',
    '이 응용 프로그램이 고유합니까?',
    '예, 귀하의 Promise 애플리케이션은 고유합니다. 블록체인 기술을 사용하므로 특별하고 흥미로워집니다.',
    '사용자가 자신의 돈만 따고 그 이상은 얻지 못한다면 왜 사용자에게 이로울 수 있습니까?',
    '사용자는 이 애플리케이션을 사용하여 더 많은 동기를 부여하고 규율을 보여줄 수 있습니다. 이러한 방식으로 사용자는 자신의 목표를 설정하고 이를 달성하도록 동기를 부여합니다. 예를 들어 사용자는 특정 페이지 매개변수를 계산하도록 독려하기 위해 높은 비율을 설정할 수 있습니다. 특정 기한 전에 성공하면 사용자는 돈뿐만 아니라 귀중한 정신 훈련도 돌려받을 것입니다.',

    '심리학적 관점에서 Promis의 유용성을 어떻게 설명할 수 있습니까?',
    'Promise 앱은 동기 부여 문제가 있고 지속적으로 작업을 미루는 사람들에게 도움이 될 수 있습니다. 지연은 영구적인 의욕 저하로 이어지는 것으로 알려져 있습니다. 증가된 동기 부여와 더 나은 시간 관리는 사람들이 보다 효율적으로 작업하고 지속적인 결과를 달성하는 데 도움이 될 수 있습니다. Promise 앱은 다음을 제공합니다. 사람들에게 특정 시간에 결과를 달성하려는 목표와 동기를 부여하여 시간 관리 기술과 효율성을 향상시킬 수 있습니다.',

    '어떤 호르몬이 관련되어 있고 어떻게 도움이 되는지.',
    'Promise 앱을 사용할 때 활성화되는 여러 호르몬이 있습니다. 주로 신체가 압력과 스트레스에 대처하는 데 도움이 되는 스트레스 호르몬인 코르티솔입니다. 혈압을 낮추고 신경계를 진정시킵니다. 엔돌핀은 또한 앱 사용자가 성공에 대한 갈망 증가를 통해 목표를 달성하고 달성하십시오. 이러한 호르몬은 앱을 사용하는 과정에서 사람을 도울 수 있습니다.',

    '부모가 자녀가 이 앱을 사용하도록 하려면 어떻게 해야 합니까?',
    '부모는 Promise 앱을 사용하여 자녀가 특정 작업을 지속적으로 수행하는 동기와 습관을 개발하도록 도울 수 있습니다. 자녀에게 특정 마감일까지 정해진 시간 동안 독서를 제공하고 성공적으로 읽을 수 있는 경우 상금을 주기만 하면 됩니다. 허용된 시간 내에 작업을 완료합니다. .이렇게 하면 동기 부여가 유지되고 작업에 열심히 노력하는 습관이 생깁니다.',
    '일반적인 방법과 비교하여 이러한 읽기 방법의 단점은 무엇입니까?',
    '이 응용 프로그램을 사용할 때 세금 문제 및 디지털 보안 문제가 있을 수 있습니다. 또한 진행 상황 추적 및 게임 규칙 간의 불일치 문제가 있을 수 있습니다. 마지막으로 사용자가 자금을 인출하고 이체하려고 할 때 문제가 발생할 수 있습니다. 정상적인 읽기 방법은 더 많은 것을 제공합니다. 책을 쉽게 구할 수 있고, 사용하기 쉬우며, 구독이 가능하고, 저렴한 가격과 같은 편의성을 제공합니다.',
    '이 앱을 사용하면 무엇이 잘못될 수 있나요?',
    '북잭 애플리케이션을 사용하면 애플리케이션의 보안이 잘못될 수 있습니다. 이로 인해 침입자가 시스템에 침입하여 데이터 무결성이 손상될 수 있습니다. 또한 애플리케이션의 성능 부족으로 인해 사용자가 응용 프로그램을 충분히 효율적으로 사용합니다. 응용 프로그램 사용자에게 충분한 기술 지원을 제공하는 것도 필요합니다.',
  ],
  العربية: [
    'ما رأيك في Promis؟',
    'يوفر تطبيق Promise للمستخدمين لعبة ممتعة وإستراتيجية تمامًا. يمكن أن تكون المقامرة التي تنطوي على عنصر مخاطرة مفيدة لتشجيع الأشخاص على قضاء المزيد من الوقت في القراءة. وربما يكون تطبيقًا رائعًا للتحفيز وتجنيد الحافز.',
    'هل هذا التطبيق فريد من نوعه؟',
    'نعم ، تطبيق Promise الخاص بك فريد من نوعه. فهو يستخدم تقنية blockchain ، مما يجعله مميزًا وممتعًا.',
    'لماذا يمكن أن يكون مفيدًا للمستخدم إذا ربح فقط أمواله الخاصة ، ولكن ليس أكثر.',
    'يمكن للمستخدم استخدام هذا التطبيق ليكون أكثر حماسًا ولإظهار الانضباط. وبهذه الطريقة ، يحدد المستخدم نفسه أهدافه ويحفزه على تحقيقها. على سبيل المثال ، يمكن للمستخدم تحديد معدلات عالية لتشجيع نفسه على حساب معلمات صفحة معينة قبل موعد نهائي معين. إذا نجح المستخدم ، فلن يعيد المال فحسب ، بل سيعود أيضًا إلى الانضباط العقلي القيّم. ',

    'كيف يمكن تفسير فائدة Promise من وجهة نظر نفسية؟',
    'يمكن أن يكون تطبيق Promise مفيدًا للأشخاص الذين لديهم مشكلات في التحفيز ويؤجلون مهامهم باستمرار. ومن المعروف أن التأخيرات تؤدي إلى إحباط دائم. ويمكن أن يساعد التحفيز المتزايد وإدارة الوقت بشكل أفضل الأشخاص على العمل بكفاءة أكبر وتحقيق نتائج دائمة. يوفر تطبيق Promise الأشخاص هدف ودافع لتحقيق نتيجة في وقت معين ، مما يسمح لهم بتحسين مهاراتهم في إدارة الوقت وكفاءتهم. ',

    'ما الهرمونات المعنية وكيف تساعد.',
    'هناك العديد من الهرمونات التي سيتم تنشيطها عند استخدام تطبيق Promise. في المقام الأول ، هرمون الإجهاد الكورتيزول ، الذي يساعد الجسم على التعامل مع الضغط والتوتر. كما أنه يخفض ضغط الدم ويهدئ الجهاز العصبي. ويمكن للإندورفين أيضًا أن يساعد مستخدم التطبيق على تعيين الهدف وتحقيقه. من خلال الرغبة المتزايدة في النجاح. يمكن أن تساعد هذه الهرمونات الشخص في عملية استخدام التطبيق. ',

    'كيف يمكن للآباء حث أطفالهم على استخدام هذا التطبيق؟',
    'يمكن للوالدين استخدام تطبيق Promise لمساعدة أطفالهم على تنمية الحافز وعادات العمل باستمرار في مهام معينة. يمكنهم ببساطة منح أطفالهم عددًا محددًا من ساعات القراءة بحلول موعد نهائي معين ومنحهم جائزة نقدية إذا تمكنوا من ذلك بنجاح أكمل المهمة في الوقت المسموح به. وهذا سيبقيهم متحفزين ويعودون على العمل الجاد في مهامهم. ',
    'ما هي عيوب هذه الطريقة في القراءة مقارنة بالطريقة المعتادة؟',
    'قد تكون هناك مشكلات ضريبية ومشكلات أمنية رقمية عند استخدام هذا التطبيق. قد تكون هناك أيضًا مشكلات في تتبع التقدم وعدم الاتساق بين قواعد اللعبة. وأخيرًا ، قد يواجه المستخدمون مشكلات عند محاولة سحب الأموال وتحويلها. تقدم الطريقة العادية للقراءة المزيد الراحة ، مثل سهولة الحصول على الكتاب ، وسهولة الاستخدام ، وتوافر الاشتراكات ، والأسعار الرخيصة. ',
    'ما الخطأ الذي يمكن أن يحدث إذا كنت تستخدم هذا التطبيق؟',
    'إذا كنت تستخدم تطبيق Book Jack ، فقد يحدث خطأ في أمان التطبيق. وقد يؤدي ذلك إلى دخول المتطفلين إلى النظام والإضرار بسلامة البيانات. أيضًا ، قد يؤدي الأداء غير الكافي للتطبيق إلى عدم قدرة المستخدمين على إجراء استخدام التطبيق بكفاءة كافية. ومن الضروري أيضًا توفير الدعم الفني الكافي لمستخدمي التطبيق. ',
  ],
  עִבְרִית: [
    'מה אתה חושב על Promise?',
    'אפליקציית Promise שלך מציעה למשתמשים משחק מהנה ודי אסטרטגי. הימורים עם אלמנט של סיכון יכולים להיות שימושיים כדי לעודד אנשים להשקיע יותר זמן בקריאה. אולי זו יכולה להיות אפליקציה מצוינת למוטיבציה ולגיוס מוטיבציה',
    ' האם האפליקציה הזו ייחודית? ',
    "כן, אפליקציית Promise שלך היא ייחודית. היא משתמשת בטכנולוגיית בלוקצ'יין, מה שהופך אותה למיוחדת ומעניינת.",
    'מדוע זה יכול להועיל למשתמש אם הוא זוכה רק בכסף שלו, אבל לא יותר.',
    'המשתמש יכול להשתמש באפליקציה הזו כדי לקבל יותר מוטיבציה ולהפגין משמעת. בדרך זו המשתמש עצמו מגדיר את המטרות שלו ומניע אותו להשיגן. לדוגמה, המשתמש יכול להגדיר שיעורים גבוהים כדי לעודד את עצמו לחשב פרמטרים מסוימים של עמודים לפני מועד מסוים. אם יצליח המשתמש יחזיר לא רק כסף, אלא גם משמעת נפשית חשובה.',

    'כיצד ניתן להסביר את התועלת של Promise מנקודת מבט פסיכולוגית?',
    'אפליקציית Promise יכולה להיות מועילה לאנשים שיש להם בעיות מוטיבציה ודוחים כל הזמן את המשימות שלהם. עיכובים ידועים כמובילים להפחתת מוטיבציה קבועה. מוטיבציה מוגברת וניהול זמן טוב יותר יכולים לעזור לאנשים לעבוד בצורה יעילה יותר ולהשיג תוצאות מתמשכות. אפליקציית Promise מספקת לאנשים מטרה ומוטיבציה להשיג תוצאה בזמן מסוים, מה שמאפשר להם לשפר את כישורי ניהול הזמן ויעילותם',

    'אילו הורמונים מעורבים וכיצד הם עוזרים.',
    'ישנם מספר הורמונים שיופעלו בשימוש באפליקציית Promise. בעיקר הורמון הסטרס קורטיזול, שעוזר לגוף להתמודד עם לחץ ולחץ. הוא מוריד לחץ דם ומרגיע את מערכת העצבים. אנדורפינים יכולים גם לעזור למשתמש באפליקציה להגדיר מטרה ולהשיג אותה. באמצעות השתוקקות מוגברת להצלחה. ההורמונים הללו יכולים לעזור לאדם בתהליך השימוש באפליקציה.',

    'איך הורים יכולים לגרום לילדים שלהם להשתמש באפליקציה הזו?',
    'הורים יכולים להשתמש באפליקציית Promise כדי לעזור לילדיהם לפתח מוטיבציה והרגל לעבוד כל הזמן על משימות מסוימות. הם יכולים פשוט לתת לילדם מספר מוגדר של שעות קריאה עד תאריך יעד מסוים ולתת להם פרס כספי אם הם מצליחים בהצלחה להשלים את המשימה בזמן המותר. זה ישמור עליהם מוטיבציה ולהרגל לעבוד קשה על המשימות שלהם.',
    'מהם החסרונות של דרך הקריאה הזו, בהשוואה לדרך הרגילה?',
    'ייתכנו בעיות מס ובעיות אבטחה דיגיטלית בעת השימוש באפליקציה הזו. ייתכנו גם בעיות במעקב אחר ההתקדמות וחוסר עקביות בין חוקי המשחק. לבסוף, משתמשים עלולים להיתקל בבעיות בעת ניסיון למשוך ולהעביר כספים. דרך הקריאה הרגילה מציעה יותר נוחות, כגון קלות השגת הספר, קלות שימוש, זמינות מינויים ותעריפים זולים.',
    'מה יכול להשתבש אם אתה משתמש באפליקציה הזו?',
    'אם אתה משתמש באפליקציית Book Jack, האבטחה של האפליקציה עלולה להשתבש. הדבר עלול להוביל לכניסת פולשים למערכת ולפגיעה בשלמות הנתונים. כמו כן, הביצועים הלא מספקים של האפליקציה עלולים לגרום לכך שמשתמשים לא יוכלו לבצע שימוש באפליקציה בצורה יעילה מספיק. יש צורך גם לספק תמיכה טכנית מספקת למשתמשי האפליקציה.',
  ],
};
